# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/latest/dbt_yml_files.json
---
integration_tests:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: "tests.duckdb"
